### ISSUE TITLE
It's not working anymore on Unity 5.6

### ISSUE THREAD

**Issue by alxcancado** [kongregate/webgl-preloader#2]
I couldn't understand very well but you can see more details in this thread:

https://forum.unity3d.com/threads/new-unity-webgl-embedding-api-white-paper.430909/

**Comment by BenV** [comment]
Thanks, we will look into adding a Unity 5.6 version soon

**Comment by BenV** [comment]
This latest release should work with Unity 5.6. The previous version can be found at https://github.com/kongregate/webgl-preloader/tree/unity-5.5-and-below
