### ISSUE TITLE
Unity 5.6 gets scrollbars at resolution 800x600

### ISSUE THREAD

**Issue by mikaelhogstrom** [kongregate/webgl-preloader#5]
Unity 5.6 gets scrollbars at resolution 800x600 when having this set in both player settings and when uploading on Kong. Should I set an extra margin when uploading or should something be added to the tamplate file?

**Comment by BenV** [comment]
This should be resolved in master with https://github.com/kongregate/webgl-preloader/commit/caa06a5a2fe84efdb3d7a9654be2510ba15c3d92, thanks for reporting that!

**Comment by mikaelhogstrom** [comment]
Tried the new commit and it works perfectly! Thanks!
